# Generated by Django 3.2.23 on 2023-12-19 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('momo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiuser_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiuser_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='product',
            field=models.ForeignKey(help_text='A product which this User authenticates', on_delete=django.db.models.deletion.CASCADE, to='momo.product'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='api_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.apiuser'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesstoken_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesstoken_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('momo.product',),
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('momo.product',),
        ),
    ]
