# Generated by Django 3.2.23 on 2023-12-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=38)),
                ('client_secret_key', models.CharField(max_length=38)),
                ('grant_type', models.CharField(choices=[('client_credentials', 'Client Credentials')], default='client_credentials', max_length=30)),
                ('pin_enc_public_key', models.TextField()),
                ('account_pin', models.CharField(help_text='Collections account PIN,Used for disbursements', max_length=4, null=True)),
                ('hash_key', models.CharField(max_length=35, null=True)),
            ],
            options={
                'db_table': 'airtel_application',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AirtelAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=30)),
                ('expires_in', models.IntegerField(default=3600)),
                ('expired', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtel.airtelapplication')),
            ],
            options={
                'db_table': 'airtel_access_token',
            },
        ),
    ]
