# Generated by Django 3.2.23 on 2023-12-19 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airtel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtelaccesstoken',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtelaccesstoken_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airtelaccesstoken',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtelaccesstoken_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
