# Generated by Django 3.2.23 on 2023-12-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
